name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          #project-token: 5aea3e685fd3447d9e3bd74a0728f3ab
          # or
          api-token: ${{ 5aea3e685fd3447d9e3bd74a0728f3ab}}
          coverage-reports: cobertura.xml
