#name: codacy-coverage-reporter

#on: ["push"]

#jobs:
 # codacy-coverage-reporter:
  #  runs-on: ubuntu-latest
  #  name: codacy-coverage-reporter
   # steps:
    #  - uses: actions/checkout@v2
     # - name: Run codacy-coverage-reporter
       # uses: codacy/codacy-coverage-reporter-action@v1
       # with:
          #project-token: 5aea3e685fd3447d9e3bd74a0728f3ab
          # or
          #api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
         # project-token: 5aea3e685fd3447d9e3bd74a0728f3ab
          #coverage-reports: cobertura.xml

name: coverage report
on:
  push:
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: e9bc34109a706c721c8b6ea1a6392c6b2f71e77758a55c22c132b8c0612465ad
      with:
        coverageCommand: yarn coverage




