name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.HOST }}
      DATAPORT: ${{ secrets.DATAPORT }}
      DATAUSER: ${{ secrets.DATAUSER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      DATABASE: ${{ secrets.DATABASE }}
      SECRETKEY: ${{ secrets.DATABASE }}
      SPOON_API: ${{ secrets.DATABASE }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Run tests
        run: npx nyc --reporter=lcov npm test
        working-directory: app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
