#name: codacy-coverage-reporter

#on: ["push"]

#jobs:
 # codacy-coverage-reporter:
  #  runs-on: ubuntu-latest
  #  name: codacy-coverage-reporter
   # steps:
    #  - uses: actions/checkout@v2
     # - name: Run codacy-coverage-reporter
       # uses: codacy/codacy-coverage-reporter-action@v1
       # with:
          #project-token: 5aea3e685fd3447d9e3bd74a0728f3ab
          # or
          #api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
         # project-token: 5aea3e685fd3447d9e3bd74a0728f3ab
          #coverage-reports: cobertura.xml
name: Node.js CI

on: push

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: TestCoverage
      id: testCoverage
      uses: anuraag016/Jest-Coverage-Diff@master
      with:
        fullCoverageDiff: false // defaults to false, if made true whole coverage report is commented with the diff
        runCommand: "npx jest --collectCoverageFrom='[\"src/**/*.{js,jsx,ts,tsx}\"]' --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit --detectOpenHandles test/.*test.*"
        delta: 0.5








