#name: codacy-coverage-reporter

#on: ["push"]

#jobs:
 # codacy-coverage-reporter:
  #  runs-on: ubuntu-latest
  #  name: codacy-coverage-reporter
   # steps:
    #  - uses: actions/checkout@v2
     # - name: Run codacy-coverage-reporter
       # uses: codacy/codacy-coverage-reporter-action@v1
       # with:
          #project-token: 5aea3e685fd3447d9e3bd74a0728f3ab
          # or
          #api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
         # project-token: 5aea3e685fd3447d9e3bd74a0728f3ab
          #coverage-reports: cobertura.xml
name: 'coverage'
on: push
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: ziishaned/jest-reporter-action@v0.0.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}







