# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    env:
      HOST: ${{ secrets.HOST }}
      DATAPORT: ${{ secrets.DATAPORT }}
      DATAUSER: ${{ secrets.DATAUSER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      DATABASE: ${{ secrets.DATABASE }}
      SECRETKEY: ${{ secrets.DATABASE }}
      SPOON_API: ${{ secrets.DATABASE }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
    - uses: actions/checkout@v2
    - name: display env
      run: |
        echo "The Host is: ${{ env.HOST }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - run: npm ci
      working-directory: app
    - run: npm run build --if-present
      working-directory: app
    - run: npm test
      working-directory: app
