name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v1
      - uses: 18f/18f-eslint-action@v1.0.0
        with:
          lint-glob: '**/*.js'
          working-directory: app

