name: linter
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
        working-directory: app
      - name: Install eslint
        run: npm install -g eslint --save-dev
        working-directory: app
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
        working-directory: app
